apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
data:
  postgres-user: {{ .Values.secret.data.postgres-user }} 
  postgres-password: {{ .Values.secret.data.postgres-password }} 
  