apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dbDeployment.name }}
  labels:
    app: {{ .Values.dbName }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.dbName }}
  template:
    metadata:
      labels:
        app: {{ .Values.dbName }}
    spec:
      containers:
      - name: scrum-postgres
        image: postgres:9.6-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: postgres-user

                
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: postgres-password 
              
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.name }}
              key: postgres-db                   
---

apiVersion: v1
kind: Service
metadata:
  name: scrum-postgres
spec:
  selector:
    app: {{ .Values.dbName }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432