apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontendDeployment.name }}
  labels:
    app: {{ .Values.frontendName }}  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.frontendName }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontendName }}
    spec:
      containers:
      - name: scrum-ui
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: scrum-ui-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.frontendName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30086  
